name: 'crm_sales_project'
version: '1.0'
config-version: 2

profile: 'crm_sales_project'


model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"


models:
  crm_sales_project:
    staging:
      +schema: STAGING
      +materialized: view

    intermediate:
      +schema: INTERMEDIATE
      +materialized: table

    core:
      +schema: CORE
      +materialized: table
